version: ~> 1.0
language: rust
dist: focal
sudo: true
group: edge
script:
  - sudo apt-get install --yes linux-modules-extra-"$(uname --kernel-release)"
  - ./scripts/ci.sh
  - cargo build --verbose
  - cargo test --verbose -- --test-threads=1
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc-10
    - ibverbs-providers
    - iproute2
    - jq
    - libibverbs-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libudev-dev
    - ninja-build
env:
  - RUST_BACKTRACE=1
rust:
  - nightly
  - beta
  - stable
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
